<a href="https://colab.research.google.com/github/krishnamanc/Pytorch/blob/main/1_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
import numpy as np

LISTS

In [ ]:
my_List = [[1,2,3,4,5], [6,7,8,9,10]]
my_List

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.86661205, 0.84371002, 0.04098269, 0.89269934],
       [0.79301256, 0.06715002, 0.71549641, 0.86052844],
       [0.38732638, 0.19141848, 0.27879017, 0.01028825]])

In [ ]:
np1.dtype

dtype('float64')

TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3446, -1.1399,  0.0411, -0.8013],
        [ 0.7368, -0.5470,  0.1047, -0.2073],
        [ 0.5807,  0.5510,  1.3086, -1.2643]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 1.0986, -1.1310,  0.0274, -2.1637],
         [-0.9287,  0.2998, -1.1229,  0.0946],
         [-0.3808, -0.7447, -0.6109,  0.2709]],

        [[-0.1985,  0.8777,  0.0113, -0.1295],
         [ 1.0803, -0.3564,  1.0342, -0.4370],
         [ 1.4736, -0.2970, -0.1555,  1.0707]]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# numpy to tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8666, 0.8437, 0.0410, 0.8927],
        [0.7930, 0.0672, 0.7155, 0.8605],
        [0.3873, 0.1914, 0.2788, 0.0103]], dtype=torch.float64)

In [ ]:
# tensors are made for running on gpu

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and view
my_torch = my_torch.reshape(10,1)
my_torch

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
# Reshape and view
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
# if you don't know the number of items there, put -1
my_torch2 = my_torch.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
newtorch = torch.arange(10)
newtorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
newtorch1 = newtorch.reshape(2,-1)
newtorch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
newtorch[1] = 4141
newtorch

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
newtorch1

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

SLICES

In [ ]:
sliceten = torch.arange(10)
sliceten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sliceten[7]

tensor(7)

In [ ]:
ressliceten = sliceten.reshape(5,2)
ressliceten

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
# : represents all elements in that one
# return 2nd row
ressliceten[1,:]

tensor([2, 3])

In [ ]:
# return 2nd column
ressliceten[:,1]

tensor([1, 3, 5, 7, 9])

TENSOR MATH

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# addition Longhand
torch.add(tensor_a , tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# div function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# exponent or power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# reassignment
tensor_a = tensor_a + tensor_b

In [ ]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])